# Generated by Django 5.2.8 on 2025-11-12 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('user', models.CharField(max_length=10)),
                ('action', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Regime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=50)),
                ('asset_identifier', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=250)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=50)),
                ('storage_location', models.CharField(max_length=50)),
                ('pediment', models.CharField(max_length=10)),
                ('invoice', models.CharField(max_length=50)),
                ('pediment_invoice_date', models.DateTimeField(verbose_name='Pediment-Invoice date')),
                ('patent', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=1024)),
                ('custom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.custom')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.customer')),
                ('regime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.regime')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.status')),
                ('tags', models.ManyToManyField(to='assets.tag')),
            ],
        ),
    ]
