# Generated by Django 4.2.26 on 2025-11-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_assetfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='motivo_salida',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
