# Generated by Django 4.2.26 on 2025-11-21 21:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0006_customerforuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CustomerForUser',
        ),
    ]
