# Generated by Django 4.2.26 on 2025-11-21 21:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0007_customer_allowed_users_delete_customerforuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
