# Generated by Django 4.2.26 on 2025-11-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_remove_customer_allowed_users_customerforuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_identifier',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='brand',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='invoice',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='model',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='notes',
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='patent',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='pediment',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='pediment_invoice_date',
            field=models.DateTimeField(default=None, null=True, verbose_name='Pediment-Invoice date'),
        ),
    ]
