# Generated by Django 4.2.26 on 2025-12-09 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_alter_asset_asset_alter_asset_asset_identifier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='asset_qr/')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr', to='assets.asset')),
            ],
        ),
    ]
